name: Release and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --with dev

      - name: Lint with pylint
        run: poetry run pylint src/

      - name: Run tests with pytest
        run: poetry run pytest tests/

  release:
    name: Version and Tag
    if: github.event_name == 'push' && github.ref_name == 'main'
    runs-on: ubuntu-latest
    needs: lint-and-test
    concurrency:
      group: release-${{ github.ref_name }}
      cancel-in-progress: false

    outputs:
      released: ${{ steps.semantic_release.outputs.released }}
      version_tag: ${{ steps.semantic_release.outputs.tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Configure Git for PAT
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}

      - name: Install semantic-release
        run: pip install python-semantic-release

      - name: Run Semantic Release
        id: semantic_release
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          semantic-release -vv version
          semantic-release -vv publish
          echo "released=true" >> $GITHUB_OUTPUT
          echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Publish GitHub Release Assets
        if: steps.semantic_release.outputs.released == 'true'
        uses: python-semantic-release/publish-action@v10.2.0
        with:
          github_token: ${{ secrets.GH_PAT }}
          tag: ${{ steps.semantic_release.outputs.tag }}

  build:
    name: Build distribution
    if: needs.release.outputs.released == 'true'
    runs-on: ubuntu-latest
    needs: release

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build tool
        run: python3 -m pip install build --user

      - name: Build distributions
        run: python3 -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-to-pypi:
    name: Publish to PyPI
    if: needs.build.result == 'success'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: pypi
      url: https://pypi.org/p/varphi-devkit
    permissions:
      id-token: write

    steps:
      - name: Download built distributions
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
