name: Release and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --with dev

      - name: Lint with pylint
        run: poetry run pylint src/

      - name: Run tests with pytest
        run: poetry run pytest tests/

  release:
    name: Semantic Release
    if: github.event_name == 'push' && github.ref_name == 'main'
    runs-on: ubuntu-latest
    needs: lint-and-test
    concurrency:
      group: release-${{ github.ref_name }}
      cancel-in-progress: false

    permissions:
      contents: write
      id-token: write

    outputs:
      released: ${{ steps.semantic_release.outputs.released }}
      tag: ${{ steps.semantic_release.outputs.tag }}

    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Reset to workflow SHA
        run: git reset --hard ${{ github.sha }}

      - name: Semantic Version Release
        id: semantic_release
        uses: python-semantic-release/python-semantic-release@v10.2.0
        with:
          github_token: ${{ secrets.GH_PAT }}
          git_committer_name: "github-actions"
          git_committer_email: "actions@users.noreply.github.com"

      - name: Upload Release Artifacts to GitHub
        if: steps.semantic_release.outputs.released == 'true'
        uses: python-semantic-release/publish-action@v10.2.0
        with:
          github_token: ${{ secrets.GH_PAT }}
          tag: ${{ steps.semantic_release.outputs.tag }}

      - name: Upload Distribution Artifacts
        if: steps.semantic_release.outputs.released == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
          if-no-files-found: error

  publish-to-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: release
    if: startsWith(github.ref, 'refs/tags/')

    permissions:
      contents: read
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/p/varphi-devkit

    steps:
      - name: Download Built Distributions
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
