name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Needed to push tags, commits, and create GitHub release

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency:
      group: release-${{ github.ref_name }}
      cancel-in-progress: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Reset to workflow commit SHA
        run: git reset --hard ${{ github.sha }}

      - name: Verify upstream has NOT changed
        shell: bash
        run: |
          set +o pipefail
          UPSTREAM_BRANCH_NAME="$(git status -sb | head -n 1 | cut -d' ' -f2 | grep -E '\.{3}' | cut -d'.' -f4)"
          echo "Upstream branch: $UPSTREAM_BRANCH_NAME"
          set -o pipefail
          git fetch "${UPSTREAM_BRANCH_NAME%%/*}"
          UPSTREAM_SHA="$(git rev-parse "$UPSTREAM_BRANCH_NAME")"
          HEAD_SHA="$(git rev-parse HEAD)"
          if [ "$HEAD_SHA" != "$UPSTREAM_SHA" ]; then
            echo "::error::Upstream branch has changed, aborting release"
            exit 1
          fi

      - name: Run Semantic Release
        id: semantic_release
        uses: python-semantic-release/python-semantic-release@v10.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_committer_name: "github-actions"
          git_committer_email: "actions@users.noreply.github.com"
          build: true

      - name: Publish GitHub Release Assets
        if: steps.semantic_release.outputs.released == 'true'
        uses: python-semantic-release/publish-action@v10.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.semantic_release.outputs.tag }}
